### ISSUE TITLE
Centraliser ressources : Roubaix

### ISSUE THREAD

**Issue by yvan-sraka** [simplonco/training#12]
> [Simplon Roubaix](https://github.com/Simplon-Roubaix)

**Reste à récupérer :** PHP, MySQL, Javascript, Symfony, AngularJS ? (ou autres)

_NB: si vous possédez d'autres repos sur différents langages (cours, challenge, projets), n'hésitez pas ! :smile:_

**Comment by enzostvs** [comment]
@didierClin

**Comment by enzostvs** [comment]
Demander à Hachemi et Thierry leurs GitHub

**Comment by yvan-sraka** [comment]
> Demander à Hachemi et Thierry leurs GitHub

@enzofly0r tu t'en occupes ?
