### ISSUE TITLE
Centraliser ressources : Marseille

### ISSUE THREAD

**Issue by yvan-sraka** [simplonco/training#13]
> [Simplon Marseille](https://github.com/silently?tab=repositories)

**Reste à récupérer :** PHP, MySQL, Javascript, Symfony, AngularJS ? (ou autres)

_NB: si vous possédez d'autres repos sur différents langages (cours, challenge, projets), n'hésitez pas ! :smile:_

**Comment by enzostvs** [comment]
@silently

**Comment by silently** [comment]
Toutes les choses publiées sont effectivement sur mon GitHub, principalement des bouts d'exos ou starters de projets.

Et les cours ou TP que j'ai eu le temps de formaliser sont dans ce repo : https://github.com/silently/simplon-wiki

**Comment by yvan-sraka** [comment]
@silently je t'ai ajouté à l'organisation @simplonco :smile: !
