### ISSUE TITLE
Centraliser ressources :  Montreuil P6

### ISSUE THREAD

**Issue by yvan-sraka** [simplonco/training#3]
> - [Simplon P6 - fullstackJS](https://gitlab.com/groups/montreuil-p6)
> - [Simplon Node API](https://gitlab.com/simplon-co/node-simple-api)

**Reste à récupéré:** PHP, MySQL, Javascript, Symfony, AngularJS ? (ou autres)

_NB: si vous possédez d'autres repos sur différents langages (cours, challenge, projets), n'hésitez pas ! :smile:_

**Comment by enzostvs** [comment]
Demander à Sara Guerric son GitHub

**Comment by yvan-sraka** [comment]
> Demander à Sara Guerric son GitHub

@enzofly0r tu t'en occupes ?
