### ISSUE TITLE
Centraliser ressources : Narbonne

### ISSUE THREAD

**Issue by yvan-sraka** [simplonco/training#4]
> [Simplon Narbonne](https://github.com/Simplon-Narbonne)

**Reste à récupérer :** PHP, MySQL, Javascript, Symfony, AngularJS ? (ou autres)

_NB: si vous possédez d'autres repos sur différents langages (cours, challenge, projets), n'hésitez pas ! :smile:_

**Comment by enzostvs** [comment]
@Boyquotes
